### ISSUE TITLE
export default env causing issues with webpack output params

### ISSUE THREAD

**Issue by artivilla** [ryandrewjohnson/boilerplate#1]
So I tried this config and I'm getting this:
```
/Users/artichandok/Dropbox/repos/mirrors/node_modules/webpack/bin/convert-argv.js:507 				throw new Error("'output.filename' is required, either in config file or as --output-filename");
Error: 'output.filename' is required, either in config file or as --output-filename
    at processOptions (/Users/artichandok/Dropbox/repos/mirrors/node_modules/webpack/bin/convert-argv.js:507:11)
    at processConfiguredOptions (/Users/artichandok/Dropbox/repos/mirrors/node_modules/webpack/bin/convert-argv.js:150:4)
    at module.exports (/Users/artichandok/Dropbox/repos/mirrors/node_modules/webpack/bin/convert-argv.js:112:10)
    at yargs.parse (/Users/artichandok/Dropbox/repos/mirrors/node_modules/webpack/bin/webpack.js:171:41)
    at Object.Yargs.self.parse (/Users/artichandok/Dropbox/repos/mirrors/node_modules/webpack/node_modules/yargs/yargs.js:533:18)
    at Object.<anonymous> (/Users/artichandok/Dropbox/repos/mirrors/node_modules/webpack/bin/webpack.js:152:7)
    at Module._compile (module.js:643:30)
    at Module._extensions..js (module.js:654:10)
    at Object.require.extensions.(anonymous function) (/Users/artichandok/Dropbox/repos/mirrors/node_modules/babel-register/lib/node.js:152:7)
    at Module.load (module.js:556:32)
```
I tried swtiching it to module.exports as well with no luck. Happy to share the project privately via codesandbox if that helps.
I set it up as follows:
```
export default env => {
	const { ifProd, ifNotProd } = getIfUtils(env)
	return {
		cache: ifNotProd(),
		entry: { app: ['babel-polyfill', 'src/index.js'] },
		devtool: ifProd('source-map', 'cheap-eval-source-map'),
		output: {
			fileName: ifProd('[name].bundle.[chunkhash].js', '[name].bundle.js'),
			path: resolve(__dirname, 'dist'),
			publicPath: '/'
		},
}
```
and I'm calling this: `"start": "concurrently -k 'node --trace-warnings -r babel-register ./node_modules/.bin/webpack --progress --env.dev --config webpack.config.babel.js' 'npm electron'",` I tried just running the first script and still no luck. Any debugging suggestions? Maybe 
 a webpack validator?

**Comment by ryandrewjohnson** [comment]
What version of webpack are you using? This config is a bit stale as this boilerplate was created around the time webpack 2 came out.

**Comment by artivilla** [comment]
Ah. v.3.11.0. This won't work with webpack 3?

**Comment by ryandrewjohnson** [comment]
I have yet to work with version 3, but you may want to give the official webpack 3 post a read. They have some info their on migrating from v2 to v3. https://medium.com/webpack/webpack-3-official-release-15fd2dd8f07b?source=linkShare-3e1c2751bed-1519012878

**Comment by ryandrewjohnson** [comment]
Also if you wanted to share codesanbox link like you mentioned I could have a look when I get a chance.

**Comment by artivilla** [comment]
Is there a way I can DM/email you the link without posting it on public chat?

**Comment by artivilla** [comment]
It's `filename` not `fileName`. 🤦‍♀️
